
// Generated by CodiumAI

import ru.job4j.calculator.Fit;

import org.junit.Test;
import static org.junit.Assert.*;

public class FitTest {


    // The 'manWeight' method returns the correct weight for a given height for a man.
    @Test
    public void test_manWeight_returns_correct_weight_for_given_height_for_man() {
        // Arrange
        short height = 187;
    
        // Act
        double result = Fit.manWeight(height);
    
        // Assert
        assertEquals(90.55, result, 0.01);
    }

    // The 'manWeight' method returns the correct weight for the minimum possible height for a man (short height = 1).
    @Test
    public void test_manWeight_returns_correct_weight_for_minimum_height_for_man() {
        // Arrange
        short height = 1;
    
        // Act
        double result = Fit.manWeight(height);
    
        // Assert
        assertEquals(-13.85, result, 0.01);
    }

}